### ISSUE TITLE
Registration does not work

### ISSUE THREAD

**Issue by karenpayneoregon** [ContextKeeper/ContextKeeper.VisualStudio#19]
Entered email address, click on link in email. Nothing happened back in VS2022.

**Comment by PiotrKarczmarz** [comment]
Thanks for reporting! Please use only **lowercase** characters when entering your email address when entering in the form and it should works fine:

![image](https://github.com/ContextKeeper/ContextKeeper.VisualStudio/assets/8102322/04ecb8c2-7aff-40da-971a-6b4ae5a6abe2)

This is a bug that I am fixing right now!

**Comment by karenpayneoregon** [comment]
For the record I used all lower-cased characters for my email address.

**Comment by PiotrKarczmarz** [comment]
Probably a typo, from the registration API logs, the first letter was capital:

![image](https://github.com/ContextKeeper/ContextKeeper.VisualStudio/assets/8102322/9242a451-6f60-43d6-ac70-979bdbf9d25a)

Please, re-enter email once again and it should work right away.
