### ISSUE TITLE
[VS 2022 v17.7] Exception when trying to create a new snapshot 

### ISSUE THREAD

**Issue by nlaslett** [ContextKeeper/ContextKeeper.VisualStudio#9]
New installation
VS 2022 v17.7
ContextKeeper v1.98.5

When I click the "Add Snapshot" button, nothing seems to happen, and I get this in the Output window:

    Error [CreateCommandHandler] Couldn't create a snapshot.
    The data necessary to complete this operation is not yet available.

VS is fully up and running, no background tasks processing.

<details><summary>Stack Trace</summary>
<p>
10:27:36.790: [ProcessId:77056] [ThreadId:1] Info [CreateCommandHandler] Creating snapshot ...
10:27:36.793: [ProcessId:77056] [ThreadId:1] Error [CreateCommandHandler] Couldn't create a snapshot.
The data necessary to complete this operation is not yet available. (Exception from HRESULT: 0x8000000A)
   at EnvDTE.Documents.GetEnumerator()
   at _lZReR5iZRC50AW97xY22UKXQdvC._rn3fbbLwHKmwPN44bkxz9IuS0KC[,,,,,,,,	,
,,,
]()
   at _427bzoGdSeRhCudkRGpFb7BdTGSA._bdjk39Ow1xrqSUrcjlf3pwpmoXF[,,,,,,,,	,
,,,
]( )
   at _vSBxehJBzTAmeoeelcokCZX9x8C._gCyaTKmElENsGObbhfSuHBhVBLj(_Fmap2tbfuju5AMXyptosO4HDXbG )
   at System.Windows.Threading.DispatcherOperation`1.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at _2HxcWNxp2BKlqioNeBz6H5crBxj._7xt4WSj6X2dMKMStIMFXbyPJXQp.MoveNext()
</p>
</details>

**Comment by PiotrKarczmarz** [comment]
Thanks for reporting! The Visual Studio version 17.7 introduced a new bug to the VS API, which was introduced the first time in 17.7 Preview 2, but has never been fixed since.

The good news is - I have working workaround, which will be released ASAP  (today or tomorrow).

**Comment by nlaslett** [comment]
Thanks for making quick work of (Microsoft's) bug!
